#!/usr/bin/env bash
# This script displays "Best School" 10 times, with "Hi" after the 9th iteration
count=0
while [ $count -lt 10 ]
do
	echo "Best School"
	((count++))
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
done
